spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paw_db_kknaks
    username: myuser
    password: 1234
    driver-class-name: org.postgresql.Driver
api:
  public-data:
    baseUrl: "http://apis.data.go.kr/1543061/animalShelterSrvc/shelterInfo"
    key: "XnvCfqp1B9c3utiwpFbA7r1fL%2FVB%2BajinxxnfzDqa9hYdr4tHh1sf0WUcxbFXSyK1HSCHQ3Llk6QLVRC9yMJ2g%3D%3D"
